config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create]
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  VALID_CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: VALID_CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true, numericality: true, inclusion: { in: (0..5)}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="alert alert-dark" role="alert">
  <h1>My list of Restaurants</h1>
</div>

<div class="row">
  <div class="col-8 offset-2">
    <div class="list-group">
      <% @restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant), class: "list-group-item list-group-item-action" do %>
          <h2><%= restaurant.name %></h2>
          <p><%= restaurant.address %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
new.html.erb

app/views/restaurants/show.html.erb
<div class="card-container col-6 offset-3">
  <div class="card" style="width: 24rem;">
    <div class="card-body">
      <h3 class="card-title">Name: <%= @restaurant.name %></h3>
      <h4 class="card-subtitle mb-2 text-muted">Category: <%= @restaurant.category %></h4>
      <p class="card-text">Address: <%= @restaurant.address %></p>
      <hr>
      <% @restaurant.reviews.each do |review|%>
      <p class="card-text">Rating: <%= review.rating %></p>
      <p class="card-text">Review: <%= review.content %></p>
    <% end %>
      <%= link_to 'Create new reviews', new_restaurant_review_path(@restaurant), class: "card-link" %>
      <%= link_to "Back to the list", restaurants_path, class: "card-link"%>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Add a review for <%= @restaurant.name %></h1>

<div class="container">
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>
</div>